# Generated by Django 5.2.4 on 2025-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeManagement', '0002_job_userinfo_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='ResumeManagement.skill'),
        ),
    ]
