# Generated by Django 5.2.4 on 2025-07-04 09:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeManagement', '0003_skill_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobDescription',
            field=tinymce.models.HTMLField(),
        ),
    ]
