# Generated by Django 5.2.4 on 2025-07-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeManagement', '0008_userinfo_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
