# Generated by Django 5.2.4 on 2025-08-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeManagement', '0010_savedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='skills',
            field=models.ManyToManyField(blank=True, to='ResumeManagement.skill'),
        ),
    ]
